core/urls.py
from django.urls import path

from .views import (
    home,
    lista_cores,
    detalhar_cor,
    salvar_cor,
    cor_delete_confirm,
    listar_uvas,
    detalhar_uva,
    uva_delete_confirm,
    salvar_uva,
    listar_vinhos,
    detalhar_vinho,
    salvar_vinho,
    vinho_delete_confirm,
    gerar_qr_code,
    gerar_qr_codeUva,
    gerar_qr_codeVinho
    
)

urlpatterns = [
    path('', home, name='core_home'),
    path('cor/', lista_cores, name='core_listar_cores'),
    path('detalhar_cor/<int:cor_id>/', detalhar_cor, name='sistema_detalhar_cor'),
    path('salvar_cor/', salvar_cor, name='core_salvar_cor'),
    path('cor_delete/<int:cor_pk>/', cor_delete_confirm, name='core_cor_delete_confirm'),
    path('qr-code/<int:cor_id>/', gerar_qr_code, name='gerar_qr_code'),

 
    path('uva/', listar_uvas, name='core_listar_uvas'),
    path('detalhar_uva/<int:uva_id>/', detalhar_uva, name='sistema_detalhar_uva'),
    path('salvar_uva/', salvar_uva, name='core_salvar_uva'),
    path('uva_delete/<int:uva_pk>/', uva_delete_confirm, name='core_uva_delete_confirm'),
    path('qr-codeUva/<int:uva_id>/', gerar_qr_codeUva, name='gerar_qr_codeUva'),
    
    path('vinho/', listar_vinhos, name='core_listar_vinhos'),
    path('detalhar_vinho/<int:vinho_id>/', detalhar_vinho, name='sistema_detalhar_vinho'),
    path('salvar_vinho/', salvar_vinho, name='core_salvar_vinho'),
    path('vinho_delete/<int:vinho_pk>/', vinho_delete_confirm, name='core_vinho_delete_confirm'),
    path('qr-codeVinho/<int:vinho_id>/', gerar_qr_codeVinho, name='gerar_qr_codeVinho'),
    
]

sommelier/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import core.urls

import core.urls

urlpatterns = [
    path('' , include('website.urls')),
    path('sistema/', include(core.urls)),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

class Uva(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.CharField(max_length=255)
    imagem = models.ImageField(upload_to='imagens/')

    def __str__(self):
        return self.nome
class Cor(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.CharField(max_length=255)
    categoria = models.CharField(max_length=50)
    created_at = models.DateField()
    updated_at = models.DateField()
    imagem = models.ImageField(upload_to='media/imagens/')

    
    def __str__(self):
        return self.nome

class Vinho(models.Model):
    nome = models.CharField(max_length=100)
    teorAlc = models.CharField(max_length=50)
    tempAmbServ = models.CharField(max_length=50)
    data = models.DateField()
    local = models.CharField(max_length=50)
    safra = models.CharField(max_length=50)
    produtor = models.CharField(max_length=100)
    paisRegiao = models.CharField(max_length=100)
    degustador = models.CharField(max_length=1000)
    rotulo = models.CharField(max_length=255)
    uva_id = models.ForeignKey('Uva', models.DO_NOTHING)
    
    def __str__(self):
        return self.nome        

core/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column
from crispy_forms.layout import Submit
from  .models import Cor, Uva, Vinho

class CorForm(forms.ModelForm):
    class Meta:
        model = Cor
        fields = ['categoria', 'created_at', 'descricao', 'id', 'imagem', 'nome', 'updated_at']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Salvar'))    
    
        
class UvaForm(forms.ModelForm):
    class Meta:
        model = Uva
        fields = '__all__'
     
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Salvar'))    
            
class VinhoForm(forms.ModelForm):
    class Meta:
        model = Vinho
        fields = [
            'nome', 'teorAlc', 'tempAmbServ', 'data', 'local', 'safra',
            'produtor', 'paisRegiao', 'degustador', 'rotulo', 'uva_id'
        ]

    def __init__(self, *args, **kwargs):
        super(VinhoForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-10'
        self.helper.layout = Layout(
            Row(
                Column('nome', css_class='form-group col-md-4 mb-0'),
                Column('teorAlc', css_class='form-group col-md-4 mb-0'),
                Column('tempAmbServ', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('data', css_class='form-group col-md-4 mb-0'),
                Column('local', css_class='form-group col-md-4 mb-0'),
                Column('safra', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('produtor', css_class='form-group col-md-4 mb-0'),
                Column('paisRegiao', css_class='form-group col-md-4 mb-0'),
                Column('degustador', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('rotulo', css_class='form-group col-md-6 mb-0'),
                Column('uva_id', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
        ) 
             
        
                        

core/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from .models import Cor, Uva, Vinho
from django.db.models import Q 
from .forms import CorForm, UvaForm, VinhoForm
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
import imghdr
from django.http import HttpResponse
import qrcode
import base64
from io import BytesIO
from django.core.paginator import Paginator



def home(request):
    context = {'mensagem' : 'Olá Ninho!'}
    return render(request, 'core/index.html', context)

def lista_cores(request):
    
    data = {}
    
    search = request.GET.get('search')
    
    if search:
        all = Cor.objects.filter(nome__icontains=search)
    else:
        all = Cor.objects.all()  
    
    paginator = Paginator(all, 4)
    pages = request.GET.get('page')
    data['db'] = paginator.get_page(pages)
    
    form = CorForm()
    data['form'] = form
    return render(request, 'core/listar_cores.html', data)


def detalhar_cor(request, cor_id):
    cor = get_object_or_404(Cor, pk=cor_id)
    data = {
        'nome': cor.nome,
        'descricao': cor.descricao,
        'categoria': cor.categoria,
        'imagem': cor.imagem.url if cor.imagem else None,
        'created_at': cor.created_at,
        'updated_at': cor.updated_at
    }
    return JsonResponse(data)

def cor_delete_confirm(request, cor_pk):
    cor = Cor.objects.get(pk=cor_pk)
    cor.delete()
    return redirect('core_listar_cores')	

def salvar_cor(request):
    
    if request.method == 'POST':
        cor_id = request.POST.get('cor_id')
        if cor_id:  # Edição de categoria existente
            cor = get_object_or_404(Cor, pk=cor_id)
            form = CorForm(request.POST, request.FILES, instance=cor)
        else:  # Novo livro
            form = CorForm(request.POST, request.FILES)
        
        if form.is_valid():
            form.save()
            return redirect('core_listar_cores')  # Redireciona após salvar
    else:
        form = CorForm()

    return render(request, 'cor_form.html', {'form': form})

def gerar_qr_code(request, cor_id):
    cor = get_object_or_404(Cor, id=cor_id)
    
    # Dados que serão incorporados no QR Code
    dados_qr = f'Nome: {cor.nome}\nDescrição: {cor.descricao}\nCategoria: {cor.categoria}'

    # Gera o QR Code
    qr = qrcode.make(dados_qr)
    buffer = BytesIO()
    qr.save(buffer, format="PNG")
    
    # Codifica a imagem como base64
    qr_code_base64 = base64.b64encode(buffer.getvalue()).decode('utf-8')
    
    # Renderiza a template com a imagem em base64
    return render(request, 'core/exibir_qrcode_cor.html', {'qr_code_base64': qr_code_base64})

#  Uvas
def listar_uvas(request):
    data = {}
    
    search = request.GET.get('search')
    
    if search:
        all = Uva.objects.filter(nome__icontains=search)
    else:
        all = Uva.objects.all()  
    
    paginator = Paginator(all, 4)
    pages = request.GET.get('page')
    data['db'] = paginator.get_page(pages)
    
    form = UvaForm()
    data['form'] = form
    return render(request, 'core/listar_uvas.html', data)


def salvar_uva(request):
    if request.method == 'POST':
        uva_id = request.POST.get('uva_id')
        if uva_id:  # Edição de autor existente
            uva = get_object_or_404(Uva, pk=uva_id)
            form = UvaForm(request.POST, request.FILES, instance=uva)
        else:  # Novo autor
            form = UvaForm(request.POST, request.FILES)
        
        if form.is_valid():
            form.save()
            return redirect('core_listar_uvas')  # Redireciona após salvar
    else:
        form = UvaForm()

    return render(request, 'uva_form.html', {'form': form})

def detalhar_uva(request, uva_id):
    uva = get_object_or_404(Uva, pk=uva_id)
    data = {
        'nome': uva.nome,
        'descricao': uva.descricao,
        'imagem': uva.imagem.url if uva.imagem else None,
        
    }
    return JsonResponse(data)

def uva_delete_confirm(request, uva_pk):
    uva = Uva.objects.get(pk=uva_pk)
    uva.delete()
    return redirect('core_listar_uvas')	

def gerar_qr_codeUva(request, uva_id):
    uva = get_object_or_404(Uva, id=uva_id)
    
    # Dados que serão incorporados no QR Code
    dados_qr = f'Nome: {uva.nome}\nDescrição: {uva.descricao}\nImagem: {uva.imagem}'

     # Gera o QR Code
    qr = qrcode.make(dados_qr)
    buffer = BytesIO()
    qr.save(buffer, format="PNG")
    
    # Codifica a imagem como base64
    qr_code_base64 = base64.b64encode(buffer.getvalue()).decode('utf-8')
    
    # Renderiza a template com a imagem em base64
    return render(request, 'core/exibir_qrcode_uva.html', {'qr_code_base64': qr_code_base64})


# Vinhos
def listar_vinhos(request):
    data = {}
    
    search = request.GET.get('search')
    
    if search:
        all = Vinho.objects.filter(nome__icontains=search)
    else:
        all = Vinho.objects.all()  
    
    paginator = Paginator(all, 4)
    pages = request.GET.get('page')
    data['db'] = paginator.get_page(pages)        
    form = VinhoForm()
    data['form'] = form

    return render(request, 'core/listar_vinhos.html', data)

def detalhar_vinho(request, vinho_id):
    vinho = get_object_or_404(Vinho, pk=vinho_id)
    data = {
        'nome': vinho.nome,
        'teorAlc':vinho.teorAlc,
        'tempAmbServ': vinho.tempAmbServ,
        'data': vinho.data,
        'local':vinho.local,
        'safra': vinho.safra,
        'produtor': vinho.produtor,
        'paisRegiao': vinho.paisRegiao,
        'degustador': vinho.degustador,
        'rotulo': vinho.rotulo,
        'uva_id': vinho.uva_id_id if vinho.uva_id_id     else None,
        
    }
    return JsonResponse(data)

def salvar_vinho(request):
    if request.method == 'POST':
        vinho_id = request.POST.get('vinho_id')
        if vinho_id:  # Edição de autor existente
            vinho = get_object_or_404(Vinho, pk=vinho_id)
            form = VinhoForm(request.POST, request.FILES, instance=vinho)
        else:  # Novo estado
            form = VinhoForm(request.POST, request.FILES)
        
        if form.is_valid():
            form.save()
            return redirect('core_listar_vinhos')  # Redireciona após salvar
    else:
        form = VinhoForm()
    print("Tentando renderizar: vinho_form.html")

    return render(request, 'vinho_form.html', {'form': form})


def vinho_delete_confirm(request, vinho_pk):
    vinho = Vinho.objects.get(pk=vinho_pk)
    Vinho.delete()
    return redirect('core_listar_vinhos')	

def gerar_qr_codeVinho(request, vinho_id):
    vinho = get_object_or_404(Vinho, id=vinho_id)
    
    # Dados que serão incorporados no QR Code
    dados_qr = f'Nome: {vinho.nome}\nTeor: {vinho.teorAlc}\nSafra: {vinho.safra}\nProdutor: {vinho.produtor}\nPaís: {vinho.paisRegiao}\nDegustador: {vinho.degustador}\nUva: {vinho.uva_id}'

     # Gera o QR Code
    qr = qrcode.make(dados_qr)
    buffer = BytesIO()
    qr.save(buffer, format="PNG")
    
    # Codifica a imagem como base64
    qr_code_base64 = base64.b64encode(buffer.getvalue()).decode('utf-8')
    
    # Renderiza a template com a imagem em base64
    return render(request, 'core/exibir_qrcode_vinho.html', {'qr_code_base64': qr_code_base64})

core/templates/core/adicionar_cor.html
<!DOCTYPE html>
<html>
<head>
    <title>Adicionar Cor</title>
</head>
<body>
    <h1>Adicionar Cor</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Salvar</button>
    </form>
</body>
</html>

core/templates/core/adicionar_uva.html
<!DOCTYPE html>
<html>
<head>
    <title>Adicionar Uva</title>
</head>
<body>
    <h1>Adicionar Uva</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Salvar</button>
    </form>
</body>
</html>

core/templates/core/base.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">


    <title>Document</title>
</head>

<body>
    <div class="container-fluid">

        {% block menu%}
        {% endblock %}
        {% block main %}
        {% endblock %}
    </div>
    

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
</body>

</html>

core/templates/core/confirmar_DelecaoUva.html
<h2>Tem certeza que deseja deletar a uva "{{ uva.nome }}"?</h2>

<form method="post">
    {% csrf_token %}
    <button type="submit">Sim, deletar</button>
    <a href="{% url 'listar_uvas' %}">Cancelar</a>
</form>

core/templates/core/confirmar_delecaoCor.html
<h2>Tem certeza que deseja deletar a cor "{{ cor.nome }}"?</h2>

<form method="post">
    {% csrf_token %}
    <button type="submit">Sim, deletar</button>
    <a href="{% url 'listar_cores' %}">Cancelar</a>
</form>

core/templates/core/confirmar_delecaoVinho.html
<h2>Tem certeza que deseja deletar o vinho "{{ vinho.nome }}"?</h2>

<form method="post">
    {% csrf_token %}
    <button type="submit">Sim, deletar</button>
    <a href="{% url 'listar_vinhos' %}">Cancelar</a>
</form>

core/templates/core/detalhar_cor.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ cores.nome }}</title>
</head>
<body>
    <h1>{{ cores.nome }}</h1>
    <p>Nome: {{ cores.nome }}</p>
    <a href="{% url 'listar_cores' %}">Voltar</a>
</body>
</html>

core/templates/core/detalhar_uva.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ uvas.nome }}</title>
</head>
<body>
    <h1>{{ uvas.nome }}</h1>
    <p>Nome: {{ uvas.nome }}</p>
    <a href="{% url 'listar_uvas' %}">Voltar</a>
</body>
</html>

core/templates/core/detalhar_vinho.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ vinhos.nome }}</title>
</head>
<body>
    <h1>{{ vinhos.nome }}</h1>
    <p>Nome: {{ vinhos.nome }}</p>
    <a href="{% url 'listar_vinhos' %}">Voltar</a>
</body>
</html>

core/templates/core/listar_cores.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


{% block menu %}
<ul class="nav nav-tabs">
	<li class="nav-item">
		<a class="nav-link" href="{% url 'core_home' %} ">Home</a>
	</li>
	<li class="nav-item active dropdown">
	<li class="nav-item dropdown">
		<a class="nav-link dropdown-toggle  active" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
			aria-expanded="false">Servicos</a>
		<div class="dropdown-menu">
			<a class="dropdown-item active" href="{% url 'core_listar_cores' %}">Cores</a>
			<a class="dropdown-item" href="{% url 'core_listar_uvas' %}">Uvas</a>
			<a class="dropdown-item" href="{% url 'core_listar_vinhos' %}">Vinhos</a>
		</div>
	</li>
	</li>
	<li class="nav-item">
		<a class="nav-link" href="{% url 'core_home' %} ">Logout</a>
	</li>

</ul>
{% endblock %}

{% block main %}


<div class="row">
	<div class="col-sm-6">
		<h1>Cadastro</h1>
		<form id="cor-form" method="POST" enctype="multipart/form-data" action="{% url 'core_salvar_cor' %}">
			{% csrf_token %}

			<input type="hidden" id="id_cor_id" name="cor_id">
			{{ form|crispy }}
			<p>

				<!-- Tag de imagem para pré-visualização -->

				<img id="id_imagem_preview"
					src="{% if form.instance.imagem %}{{ form.instance.imagem.url }}{% else %}# {% endif %}"
					alt="Imagem da Cor" width="100">

			</p>
			<p>
				{% if cor.id %}
					<a href="{% url 'core_gerar_qr_code' cor.id %}">Gerar QR Code</a>
				{% else %}
					<span>QR Code não disponível</span>
				{% endif %}
			</p>
			<button type="submit" class="btn btn-primary">Cadastrar</button>
		</form>
	</div>

	<div class="col-sm-6">
		<h1>Lista Cores</h1>
		<div class="col-8  m-auto pt-3 pb-2 text-center">
			<form method="get">
				<input type="text" name="search" placeholder="Buscar por nome, descrição ou categoria..."
					value="{{ request.GET.search }}">

			</form>
		</div>
		<table class="table">
			<thead class="thead-dark">
				<tr>
					<th scope="col">ID</th>
					<th><a
							href="?search={{ request.GET.search }}&order_by=nome&direction={% if request.GET.direction == 'asc' %}desc{% else %}asc{% endif %}">Nome</a>
					</th>
					<th><a
							href="?search={{ request.GET.search }}&order_by=categoria&direction={% if request.GET.direction == 'asc' %}desc{% else %}asc{% endif %}">Descrição</a>
					</th>
					<th><a
							href="?search={{ request.GET.search }}&order_by=descricao&direction={% if request.GET.direction == 'asc' %}desc{% else %}asc{% endif %}">Categoria</a>
					</th>
					
					<th scope="col">QR Code</th>
					<th scope="col">Ação</th>
				</tr>
			</thead>
			<tbody>
				{% for cor in db %}
				<tr data-id="{{ cor.id }}" class="cor-row">
					<td>{{ cor.id}}</td>
					<td>{{ cor.nome}}</td>
					<td>{{ cor.descricao}}</td>
					<td>{{ cor.categoria}}</td>
					
					<td><a class="btn btn-primary" href="{% url 'gerar_qr_code' cor.id %}"><i class="fas fa-qrcode"></i> QRCode</a></td>
					<td>
						<a class="btn btn-danger" href="{% url 'core_cor_delete_confirm' cor.id%}"
							onClick="return confirm('Tem certeza que deseja excluir este cor?') ">Deletar</a>
					</td>
				</tr>
				{% endfor %}

			</tbody>
		</table>
		
		<div class="pagination">
			{% if db.has_previous %}
			<a href="?page={{db.previous_page_number}}"> Previous </a>
			{% endif %}

			{{ db.number}}

			{% if db.has_next %}
			<a href="?page={{db.next_page_number}}"> Next </a>
			{% endif %}
		</div> 
		
		<div>
		</div>
		<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
		<script>
			$(document).ready(function () {
				// Quando um item da tabela é clicado
				$('.cor-row').on('click', function () {
					var corId = $(this).data('id');
					var url = '/sistema/detalhar_cor/' + corId + '/';

					// Realiza a requisição AJAX
					$.ajax({
						url: url,
						method: 'GET',
						success: function (data) {
							// Preenche o formulário com os dados do cor
							$('#id_cor_id').val(corId);  // Armazena o ID do livro
							$('#id_nome').val(data.nome);
							$('#id_descricao').val(data.descricao);
							$('#id_categoria').val(data.categoria);
							if (data.imagem) {
								$('#id_imagem_preview').attr('src', data.imagem);
							} else {
								$('#id_imagem_preview').attr('src', '');  // Limpa o preview se não houver imagem
							}

							$('#id_created_at').val(data.created_at);
							$('#id_updated_at').val(data.updated_at);

						}
					});
				});
			});

		</script>	
		
	</div>
	{% endblock %}

core/templates/core/listar_vinhos.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">


{% block menu %}
<ul class="nav nav-tabs">
	<li class="nav-item">
		<a class="nav-link" href="{% url 'core_home' %} ">Home</a>
	</li>
	<li class="nav-item active dropdown">
	<li class="nav-item dropdown">
		<a class="nav-link dropdown-toggle  active" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
			aria-expanded="false">Servicos</a>
		<div class="dropdown-menu">
			<a class="dropdown-item active" href="{% url 'core_listar_cores' %}">Cores</a>
			<a class="dropdown-item" href="{% url 'core_listar_uvas' %}">Uvas</a>
			<a class="dropdown-item" href="{% url 'core_listar_vinhos' %}">Vinhos</a>
		</div>
	</li>
	</li>
	<li class="nav-item">
		<a class="nav-link" href="{% url 'core_home' %} ">Logout</a>
	</li>

</ul>
{% endblock %}

{% block main %}


<div class="row">
	<div class="col-sm-6">
		<h1>Cadastro</h1>
		<form id="vinho-form" method="POST" enctype="multipart/form-data" action="{% url 'core_salvar_vinho' %}">
			{% csrf_token %}

			<input type="hidden" id="id_vinho_id" name="vinho_id">
			{{ form|crispy }}
			
			
			<button type="submit" class="btn btn-primary">Cadastrar</button>
		</form>
	</div>

	<div class="col-sm-6">
		<h1>Lista Vinhos</h1>
		<div class="col-8  m-auto pt-3 pb-2 text-center">
			<form method="get">
				<input type="text" name="search" placeholder="Buscar por nome, descrição ou categoria..." value="{{ request.GET.search }}">

			</form>
		</div>
		<table class="table" >
			<thead class="thead-dark" >
				<tr>
					<th scope="col">ID</th>
					<th><a href="?search={{ request.GET.search }}&order_by=nome&direction={% if request.GET.direction == 'asc' %}desc{% else %}asc{% endif %}">Nome</a></th>
					<th scope="col">Teor Alcólico</th>
					<th scope="col">Temperatura</th>
                    <th scope="col">Data</th>
					<th scope="col">QR Code</th>
					<th scope="col">Ação</th>			
			</thead>
			<tbody>
				{% for vinho in db %}
				<tr data-id="{{ vinho.id }}" class="vinho-row">
					<td>{{ vinho.id}}</td>
                    <td>{{ vinho.nome}}</td>
					<td>{{ vinho.teorAlc}}</td>
					<td>{{ vinho.tempAmbServ}}</td>
                    <td>{{ vinho.data}}</td>
                   
					<td><a class="btn btn-primary"  href="{% url 'gerar_qr_codeVinho' vinho.id %}"><i class="fas fa-qrcode"></i> QRCode</a></td>
					<td>
						<a class="btn btn-danger" href="{% url 'core_vinho_delete_confirm' vinho.id%}"
						onClick="return confirm('Tem certeza que deseja excluir este vinho?') ">Deletar</a>
					</td>
				</tr>
				{% endfor %}

			</tbody>
		</table>
		<div class="pagination">
			{% if db.has_previous %}
				<a href="?page={{db.previous_page_number}}"> Previous </a>
			{% endif %}
			
			{{ db.number}}
			
			{% if db.has_next %}
				<a href="?page={{db.next_page_number}}"> Next </a>
			{% endif %}
		</div>
		<div>
		</div>
		<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
		<script>
			$(document).ready(function () {
				// Quando um item da tabela é clicado
				$('.vinho-row').on('click', function () {
					var vinhoId = $(this).data('id');
					var url = '/sistema/detalhar_vinho/' + vinhoId + '/';

					// Realiza a requisição AJAX
					$.ajax({
						url: url,
						method: 'GET',
						success: function (data) {
							// Preenche o formulário com os dados do cor
							$('#id_vinho_id').val(vinhoId);  // Armazena o ID do livro
							$('#id_nome').val(data.nome);
                            $('#id_teorAlc').val(data.teorAlc);
                            $('#id_tempAmbServ').val(data.tempAmbServ);
                            $('#id_data').val(data.data);
                            $('#id_local').val(data.local);
                            $('#id_safra').val(data.safra);
                            $('#id_produtor').val(data.produtor);
                            $('#id_paisRegiao').val(data.paisRegiao);
                            $('#id_degustador').val(data.degustador);
                            $('#id_rotulo').val(data.rotulo);
							$('#id_uva_id').val(data.uva_id);
     		            }
		            });
	            });
			});

		</script>
		
		{% endblock %}